apiVersion: apps/v1
kind: Deployment
metadata:
  name: prezzbackend-deployment
  labels:
    app: prezzbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prezzbackend
  template:
    metadata:
      labels:
        app: prezzbackend
    spec:
      containers:
      - name: prezzbackend
        image: sriraamraj/prezz_backend:latest
        ports:
        - containerPort: 6969
