apiVersion: v1
kind: Service
metadata:
  name: prezzbackend-service
spec:
  selector:
    app: prezzbackend
  ports:
    - protocol: TCP
      port: 6969
      targetPort: 6969
      nodePort: 31112
  type: NodePort 
